services:
  web-scraping:
    container_name: web_scraping_service
    image: bitezone/web-scraping
    build: ./
    environment:
      ENV: deployment
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
