name: Deploy to EC2

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::719136958881:role/bitezone_web_scraping_github_actions_role
          aws-region: us-east-1

      - name: Pull latest code via SSM
        run: |
          aws ssm send-command \
            --targets "Key=instanceIds,Values=${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy: git pull and log" \
            --parameters 'commands=[
              "cd /home/ec2-user/BiteZoneWebScraping",
              "git pull origin main",
              "echo Pulled at $(date) >> /home/ec2-user/logs/web_scraping_deploy_logs.txt"
            ]'
